### ISSUE TITLE
Add a converter for python arrays

### ISSUE THREAD

**Issue by hinerm** [scijava/scripting-jython#2]
Currently passing a python array results in it being wrapped in a single Java object. We should add a converter implementation to automatically unwrap python arrays to Java arrays.

Without a converter, python arrays have to be explicitly unwrapped, e.g.:

```
from jarray import array
blank=ops.createimg(array([100, 50], 'l'))
```

(thanks @bnorthan for that!)

**Comment by hinerm** [comment]
@ctrueden as far as I can tell the `ConvertService` is only invoked on the [return value of a script](https://github.com/scijava/scijava-common/blob/scijava-common-2.40.0/src/main/java/org/scijava/script/ScriptModule.java#L196)... so wouldn't automatic conversion within a script require modifications to jython itself?

Per [the JArray docs](http://www.jython.org/archive/21/docs/jarray.html) I think @bnorthan's solution may be the only one currently available.

Let me know if I'm missing anything..

**Comment by ctrueden** [comment]
@hinerm The OPS framework does [convert input values as needed](https://github.com/imagej/imagej-ops/blob/imagej-ops-0.11.0/src/main/java/net/imagej/ops/DefaultOpMatchingService.java#L388).

Regarding modules in general, you're right that inputs are not auto-converted, though see scijava/scijava-common#122 and scijava/scijava-common@290ce632c00be50d713e4967d7fc840138a376d5.

**Comment by hinerm** [comment]
>The OPS framework does convert input values as needed.

Sorry, right I forgot about inputs. But any statements in the script itself, such as local variable creation in this case, are never touched by converters.

**Comment by ctrueden** [comment]
See also imagej/imagej-ops#19, which will make things more complex once it is resolved: we will need to make sure that the `OpService` built-in methods have the proper type signatures.

**Comment by ctrueden** [comment]
> But any statements in the script itself, such as local variable creation in this case, are never touched by converters.

I'm not sure I understand the concern. Can you give an example?

**Comment by hinerm** [comment]
@ctrueden and I talked briefly offline. We were talking about different things - we can't solve the general case (anonymous object creation in python) but we **can** solve the Ops case, because ops automatically converts it's inputs - which is awesome!

We also should add "goodies" converters like this for other languages' wrapped types.

**Comment by hinerm** [comment]
May be redundant after https://github.com/imagej/imagej-ops/pull/115 which remedies the actual problem that started this issue.
