### ISSUE TITLE
Update to Jython 2.7.0

### ISSUE THREAD

**Issue by ctrueden** [scijava/scripting-jython#3]
Jython 2.7.0 was released. We should upgrade to it—but only after the SciJava software stack has its minimum Java version brought up to Java 7.

**Comment by hadim** [comment]
Updating to Jython 2.7 would be great !

**Comment by hadim** [comment]
Oh I just realized Python 2.7 has already been merged. So why Fiji `sys.version` returns me 2.5.3 ?

Maybe new `scripting-jython` version has not been changed in some parent POM ?

**Comment by hadim** [comment]
My Fiji wasn't updated :-)

I guess you can close here. Sorry for the noise.

**Comment by ctrueden** [comment]
No worries, @hadim. In your defense, I finally quietly uploaded that update yesterday: ImageJ 2.0.0-rc-54 was still on 2.5.3, whereas 2.0.0-rc-56 updates to 2.7.0. (And I never uploaded 2.0.0-rc-55 to end users.)

**Comment by ctrueden** [comment]
If you are feeling industrious, you could make a News post about the update to Jython 2.7.0. Name the wiki page the same as others linked from https://imagej.net/News with the leading datestamp in that format, and add `[[Category:News]]` at the bottom of the wiki page. Then it will appear in the News feed. And you can tweet the link too with `#imagej` if you wish. I would then retweet it as `@FijiSc` and it would appear on the [Fiji front page](https://fiji.sc/) feed.

But if you don't have time, I understand, and will try to take care of announcing it later.
