### ISSUE TITLE
Consider using the JSR-223 ScriptEngine shipped with Jython

### ISSUE THREAD

**Issue by ctrueden** [scijava/scripting-jython#4]
Right now, this component provides its own JSR-223 `ScriptEngine`, which has pros and cons compared to the one shipped with Jython. IIRC, I tried Jython's built-in `ScriptEngine` but it had blocking issues. However, in conjunction with #3 (i.e., once we have updated to Jython 2.7.0), we can try again. It would be simpler to avoid our own implementation, which behaves differently from the official implementation. (For example: I am guessing 2a4d4dcc9f58c04ac31150eb8bb941f13deb9dd6 would not have been necessary were we using the built-in `ScriptEngine`.)

**Comment by hinerm** [comment]
This issue was originally blocked due to a bug in the [jython script engine](http://sourceforge.net/p/jython/mailman/jython-users/thread/54370FE9.5010603%40farowl.co.uk/).

It looks like this has been resolved and we can migrate as soon as we update to Java 7.

**Comment by hinerm** [comment]
see https://github.com/scijava/scripting-jython/tree/jsr-223-engine

**Comment by hinerm** [comment]
@ctrueden fyi using the JSR-223 engine had no effect on http://fiji.sc/bugzilla/show_bug.cgi?id=1203. That bug [required a different approach](https://github.com/scijava/scripting-jython/pull/7)

**Comment by ctrueden** [comment]
Done in c8e8fdef345779c588fb1eaeb02d91f8e3feaedc.
