### ISSUE TITLE
ImageCalculator.run method not accepting options

### ISSUE THREAD

**Issue by mparada** [scijava/scripting-jython#5]
`ImageCalculator` method `run` does not accept options. OTH, the deprecated method `calculate` does.

    from ij import IJ
    from ij.plugin import ImageCalculator

    IJ.run("Blobs (25K)");
    imp = IJ.getImage();

    # this doesn't work
    ImageCalculator().run("Subtract create", imp, imp) 

    # these work
    ImageCalculator().run("Subtract", imp, imp) # without options
    ImageCalculator().calculate("Subtract create", imp, imp) # deprecated method

**Comment by ctrueden** [comment]
This is an issue with ImageJ 1.x, so I migrated it there: imagej/imagej1#10.
